
public class Exception4
 {
    public static void main(String[] args) 
    {
        try
        {
           
        }
        catch(ArrayIndexOutOfBoundsException obj)
        {
           
        }
        catch(ArithmeticException obj)
        {

        }
        //Generic Catch Block:
        
        catch(Exception obj) // if we write it first it will give error
        {
            
        }
        finally
        {
            System.out.println("Inside finally block");
        }

        System.out.println("end of the code!!");
    }
}
        

    

